version: 2.1

setup: true

executors:
  buildpack-deps:
    docker:
      - image: cimg/base:stable

orbs:
  terraform: circleci/terraform@3.2.1
  dynamic: hqo/dynamic-continuation@1.4.10

jobs:
  tf_check_fmt:
    executor: buildpack-deps
    steps:
      - checkout
      - terraform/install:
          terraform_version: 1.5.3
      - run:
          name: Check terraform formatting for all scripts
          command: terraform fmt -check -recursive -diff

workflows:
  on-commit:
    jobs:

      - tf_check_fmt:
          name: format check

      - dynamic/continue:
          name: setup dynamic workflows
          context: orb-publishing
          modules: |
            aws
            tfc
